kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: grafana-view-only
rules:
- apiGroups:
  - grafana.integreatly.org/v1beta1
  resources:
  - grafanas
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-view-only
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-view-only
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: konflux-grafana-viewers
