kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: grafana-view-only
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  resourceNames: ["appstudio-grafana"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: grafana-view-only
  namespace: appstudio-grafana
subjects:
- kind: Group
  name: konflux-grafana-viewers
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: grafana-view-only
  apiGroup: rbac.authorization.k8s.io
