apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- namespace.yaml
- rbac.yaml
- service.yaml
- network_policy.yaml
namespace: namespace-lister
images:
- name: namespace-lister
  newName: quay.io/konflux-ci/namespace-lister
  newTag: ae5db7ec4593c91d4f4efc8ca991b83355a1202d
patches:
- path: ./patches/with-header-auth-email.yaml
  target:
    group: apps
    kind: Deployment
    name: namespace-lister
    namespace: namespace-lister
