apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: ingresscontroller
spec:
  generators:
    - merge:
        mergeKeys:
          - nameNormalized
        generators:
          - clusters:
              values:
                sourceRoot: configs/ingresscontroller
                environment: staging
                clusterDir: ""
          - list:
              elements:
                - nameNormalized: stone-prd-host1
                  values.clusterDir: stone-prd-host1
                - nameNormalized: stone-stg-host
                  values.clusterDir: stone-stg-host
  template:
    metadata:
      name: ingresscontroller-{{nameNormalized}}
    spec:
      project: default
      source:
        path: '{{values.sourceRoot}}/{{values.environment}}/{{values.clusterDir}}'
        repoURL: https://github.com/redhat-appstudio/infra-deployments.git
        targetRevision: main
      destination:
        namespace: openshift-ingress-operator
        server: '{{server}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=false
        retry:
          limit: -1
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
