---
- op: replace
  path: /spec/template/spec/source/repoURL
  value: https://github.com/redhat-hac-qe/infra-deployments
- op: replace
  path: /spec/template/spec/source/targetRevision
  value: preview-add_gobin_to_path
