---
- op: replace
  path: /spec/template/spec/sources/1/repoURL
  value: https://github.com/redhat-hac-qe/infra-deployments
- op: replace
  path: /spec/template/spec/sources/1/targetRevision
  value: preview-main
