apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: postgres
  namespace: openshift-gitops
spec:
  destination:
    namespace: tekton-results
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: postgresql
    helm:
      parameters:
      - name: image.tag
        value: 13.14.0
      - name: tls.enabled
        value: "true"
      - name: tls.certificatesSecret
        value: postgresql-tls
      - name: tls.certFilename
        value: tls.crt
      - name: tls.certKeyFilename
        value: tls.key
      - name: auth.database
        value: tekton_results
      - name: auth.username
        value: tekton
      - name: auth.existingSecret
        value: tekton-results-database
      - name: auth.secretKeys.userPasswordKey
        value: db.password
      - name: auth.secretKeys.adminPasswordKey
        value: db.password
      - name: primary.resources.requests
        value: "null"
      - name: primary.podSecurityContext.fsGroup
        value: "null"
      - name: primary.podSecurityContext.seccompProfile.type
        value: RuntimeDefault
      - name: primary.containerSecurityContext.runAsUser
        value: "null"
      - name: primary.containerSecurityContext.allowPrivilegeEscalation
        value: "false"
      - name: primary.containerSecurityContext.runAsNonRoot
        value: "true"
      - name: primary.containerSecurityContext.seccompProfile.type
        value: RuntimeDefault
      - name: primary.containerSecurityContext.capabilities.drop[0]
        value: ALL
      - name: volumePermissions.enabled
        value: "false"
      - name: shmVolume.enabled
        value: "false"
      releaseName: postgres
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 14.0.5
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
      limit: -1
    syncOptions:
    - CreateNamespace=false
    - Validate=false
