apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ../../base/external-secrets
- https://github.com/konflux-ci/integration-service/config/default?ref=f3668b96c999ad3487c103940f45e94b6d2e976b
- https://github.com/konflux-ci/integration-service/config/snapshotgc?ref=f3668b96c999ad3487c103940f45e94b6d2e976b

images:
- name: quay.io/konflux-ci/integration-service
  newName: quay.io/konflux-ci/integration-service
  newTag: f3668b96c999ad3487c103940f45e94b6d2e976b

configMapGenerator:
- name: integration-config
  literals:
    - CONSOLE_NAME="Red Hat Konflux"
    - CONSOLE_URL="https://console.redhat.com/application-pipeline/ns/{{ .Namespace }}/pipelinerun/{{ .PipelineRunName }}"
    - CONSOLE_URL_TASKLOG="https://console.redhat.com/application-pipeline/ns/{{ .Namespace }}/pipelinerun/{{ .PipelineRunName }}/logs/{{ .TaskName }}"
- name: pipelinerun-options
  literals:
    - PIPELINE_TIMEOUT="6h"
    - TASKS_TIMEOUT="4h"
    - FINALLY_TIMEOUT="2h"

namespace: integration-service

patches:
  - path: pipelines-as-code-secret.yaml
    target:
      name: pipelines-as-code-secret
      kind: ExternalSecret
      group: external-secrets.io
      version: v1beta1
  - path: manager_resources_patch.yaml
