apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cost-management
spec:
  generators:
    - merge:
        mergeKeys:
          - nameNormalized
        generators:
          - clusters:
              values:
                sourceRoot: components/cost-management
                environment: ""
                clusterDir: ""
          - list:
              elements: []
  template:
    metadata:
      name: cost-management-{{nameNormalized}}
    spec:
      project: default
      source:
        path: '{{values.sourceRoot}}/{{values.environment}}/{{values.clusterDir}}'
        repoURL: https://github.com/redhat-appstudio/infra-deployments.git
        targetRevision: main
      destination:
        namespace: costmanagement-metrics-operator
        server: '{{server}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 50
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
