apiVersion: v1
kind: ConfigMap
metadata:
  name: build-pipeline-config
  namespace: build-service
data:
  config.yaml: |
    default-pipeline-name: docker-build-oci-ta
    pipelines:
    - name: fbc-builder
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-fbc-builder:3462d3e74e91553973abccd5f07728e265b64e51
      additional-params:
      - build-platforms
    - name: docker-build
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build:3462d3e74e91553973abccd5f07728e265b64e51
    - name: docker-build-oci-ta
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build-oci-ta:3462d3e74e91553973abccd5f07728e265b64e51
    - name: docker-build-multi-platform-oci-ta
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-docker-build-multi-platform-oci-ta:3462d3e74e91553973abccd5f07728e265b64e51
      additional-params:
      - build-platforms
    - name: maven-zip-build
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-maven-zip-build:84b3cd21b9cc194838dd310fedcc316ea8a4aab4
    - name: maven-zip-build-oci-ta
      bundle: quay.io/konflux-ci/tekton-catalog/pipeline-maven-zip-build-oci-ta:84b3cd21b9cc194838dd310fedcc316ea8a4aab4
