apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: multi-platform-controller
resources:
- ../base
- host-config.yaml

patches:
- path: aws-account.patch.yaml
  target:
    kind: ExternalSecret
    name: aws-account
- path: aws-ssh-key.patch.yaml
  target:
    kind: ExternalSecret
    name: aws-ssh-key
