apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-service-controller-manager
spec:
  template:
    spec:
      containers:
      - name: manager
        env:
          - name: SEALIGHTS_TOKEN
            valueFrom:
              secretKeyRef:
                name: sealights-token
                key: token
