apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
patches:
  - path: starting-csv-patch.yaml
    target:
      name: external-secrets-operator
      group: operators.coreos.com
      version: v1alpha1
      kind: Subscription
  - path: resource-requests.patch.yaml
    target:
      name: cluster
      group: operator.external-secrets.io
      version: v1alpha1
      kind: OperatorConfig
