---
- op: add
  path: /spec/platforms/openshift/pipelinesAsCode/settings
  value:
    application-name: Konflux kflux-prd-rh02 
    custom-console-name: Konflux kflux-prd-rh02
    custom-console-url: TBA
    custom-console-url-pr-details: https://TBA/ns/{{ namespace }}/pipelinerun/{{ pr }}
    custom-console-url-pr-tasklog: https://TBA/application-pipeline/ns/{{ namespace }}/pipelinerun/{{ pr }}/logs/{{ task }}
