---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: m6a-4xlarge
  namespace: proactive-scaler
spec:
  replicas: 2
  selector:
    matchLabels:
      run: m6a-4xlarge
  template:
    metadata:
      labels:
        run: m6a-4xlarge
    spec:
      nodeSelector:
        konflux-ci.dev/workload: konflux-tenants
      tolerations:
        - key: konflux-ci.dev/workload
          operator: "Equal"
          value: "konflux-tenants"
          effect: "NoSchedule"
      priorityClassName: proactive-scaler-pods
      containers:
        - name: reserve-resources
          image: registry.k8s.io/pause
          resources:
            requests:
              memory: "45Gi"
              cpu: "10"
