apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: redhat-external
spec:
  instanceSelector:
    matchLabels:
      appstudio.redhat.com/keycloak: dev
  realm:
    accessTokenLifespan: 7200
    displayName: Redhat External for HAC
    enabled: true
    id: hac-sso
    loginTheme: rh-sso
    realm: redhat-external
    users:
      - credentials:
          - type: password
            value: user1
        email: user1@user.us
        emailVerified: true
        enabled: true
        firstName: user1
        id: user1
        username: user1
        clientRoles:
          realm-management:
            - "manage-users"
