apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: redhat-external
spec:
  instanceSelector:
    matchLabels:
      appstudio.redhat.com/keycloak: dev
  realm:
    accessTokenLifespan: 7200
    clients:
      - enabled: true
        redirectUris:
          - '*'
        clientId: cloud-services
        name: cloud-services
        implicitFlowEnabled: false
        publicClient: true
        standardFlowEnabled: true
        protocol: openid-connect
        webOrigins:
          - '*'
        directAccessGrantsEnabled: true
        defaultClientScopes: 
          - nameandterms
          - email
          - profile
          - roles
          - web-origins
        optionalClientScopes:
          - address
          - microprofile-jwt
          - offline_access
          - phone
    clientScopes:
      - name: nameandterms
        protocol: openid-connect
      - name: email
        protocol: openid-connect
    displayName: Redhat External for HAC
    enabled: true
    id: hac-sso
    loginTheme: rh-sso
    realm: redhat-external
    users:
      - credentials:
          - type: password
            value: user1
        email: user1@user.us
        emailVerified: true
        enabled: true
        firstName: user1
        id: user1
        username: user1
