---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: namespace-claim-cleaner
  namespace: crossplane-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namespace-claim-cleaner
rules:
  - apiGroups:
      - eaas.konflux-ci.dev
    resources:
      - namespaces
    verbs:
      - list
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-claim-cleaner
subjects:
  - kind: ServiceAccount
    name: namespace-claim-cleaner
    namespace: crossplane-system
roleRef:
  kind: ClusterRole
  name: namespace-claim-cleaner
  apiGroup: rbac.authorization.k8s.io
