apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - cluster-as-a-service
  - crossplane-config
components:
  - ../../k-components/deploy-to-eaas-cluster-merge-generator
  - ../../k-components/inject-argocd-namespace
