apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
namespace: mintmaker
patches:
  - path: pipelines-as-code-secret-path.yaml
    target:
      name: pipelines-as-code-secret
      group: external-secrets.io
      version: v1beta1
      kind: ExternalSecret
  - path: cronjob-patch.yaml
    target:
      name: create-dependencyupdatecheck
      kind: CronJob

components:
  - ../../components/rh-certs
