apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: konflux-ui
spec:
  generators:
    - merge:
        mergeKeys:
          - nameNormalized
        generators:
          - clusters:
              values:
                sourceRoot: components/konflux-ui
                environment: staging
                # This app must have cluster specific configurations
                clusterDir: does-not-exist
          - list:
              elements:
                - nameNormalized: stone-stg-rh01
                  values.clusterDir: stone-stg-rh01
  template:
    metadata:
      name: konflux-ui-{{nameNormalized}}
    spec:
      project: default
      source:
        path: '{{values.sourceRoot}}/{{values.environment}}/{{values.clusterDir}}'
        repoURL: https://github.com/redhat-appstudio/infra-deployments.git
        targetRevision: main
      destination:
        namespace: konflux-ui
        server: '{{server}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: -1
          backoff:
            duration: 10s
            factor: 2
            maxDuration: 3m
