apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - costmanagement-metrics-operator.yaml
  - costmanagement-metrics-config.yaml

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
